/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mojing_control.proto */

#ifndef PROTOBUF_C_mojing_5fcontrol_2eproto__INCLUDED
#define PROTOBUF_C_mojing_5fcontrol_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SwMojingControl__UploadDeviceInfoRequest SwMojingControl__UploadDeviceInfoRequest;
typedef struct _SwMojingControl__CloudStorageInfoChangeNotify SwMojingControl__CloudStorageInfoChangeNotify;
typedef struct _SwMojingControl__Pong SwMojingControl__Pong;
typedef struct _SwMojingControl__RegisterResponseWithNonce SwMojingControl__RegisterResponseWithNonce;
typedef struct _SwMojingControl__GetCloudStorageAddrRequest SwMojingControl__GetCloudStorageAddrRequest;
typedef struct _SwMojingControl__CloudStorageEndNotify SwMojingControl__CloudStorageEndNotify;
typedef struct _SwMojingControl__GetCloudStorageInfoRequest SwMojingControl__GetCloudStorageInfoRequest;
typedef struct _SwMojingControl__GetCloudStorageInfoResponse SwMojingControl__GetCloudStorageInfoResponse;
typedef struct _SwMojingControl__RegisterRequest SwMojingControl__RegisterRequest;
typedef struct _SwMojingControl__DeviceUpdateRequest SwMojingControl__DeviceUpdateRequest;
typedef struct _SwMojingControl__DeviceUpdateNotify SwMojingControl__DeviceUpdateNotify;
typedef struct _SwMojingControl__Ping SwMojingControl__Ping;
typedef struct _SwMojingControl__FromatSDCardRequest SwMojingControl__FromatSDCardRequest;
typedef struct _SwMojingControl__RegisterResponse SwMojingControl__RegisterResponse;
typedef struct _SwMojingControl__GetSDCardInfoRequest SwMojingControl__GetSDCardInfoRequest;
typedef struct _SwMojingControl__FromatSDCardStatNotify SwMojingControl__FromatSDCardStatNotify;
typedef struct _SwMojingControl__DownLoadStatRequest SwMojingControl__DownLoadStatRequest;
typedef struct _SwMojingControl__UploadDeviceInfoResponse SwMojingControl__UploadDeviceInfoResponse;
typedef struct _SwMojingControl__DeviceUpdateResponse SwMojingControl__DeviceUpdateResponse;
typedef struct _SwMojingControl__RegisterRequestWithAuth SwMojingControl__RegisterRequestWithAuth;
typedef struct _SwMojingControl__GetSDCardInfoResponse SwMojingControl__GetSDCardInfoResponse;
typedef struct _SwMojingControl__OperateResponse SwMojingControl__OperateResponse;
typedef struct _SwMojingControl__GetCloudStorageAddrResponse SwMojingControl__GetCloudStorageAddrResponse;


/* --- enums --- */


/* --- messages --- */

struct  _SwMojingControl__UploadDeviceInfoRequest
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *设备名(OSD信息)
   */
  char *devicename;
  /*
   *固件版本信息
   */
  char *firmwareversion;
  /*
   *固件文件MD5码
   */
  char *firmwaremd5;
  /*
   *软件版本信息
   */
  char *softwareversion;
  /*
   *软件文件MD5码
   */
  char *softwaremd5;
};
#define SW_MOJING_CONTROL__UPLOAD_DEVICE_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__upload_device_info_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__CloudStorageInfoChangeNotify
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *云存类型(0:不云存,1:全天存储,2:动态存储)
   */
  int32_t cloudstoragetype;
  /*
   *码流类型(0:主码流,1:辅码流,2:第三码流)
   */
  int32_t streamtype;
  /*
   *动态存储使用-预存时间(秒) 0-10
   */
  int32_t prestoragetime;
  /*
   *动态存储使用-存储持续时间(秒)30-300
   */
  int32_t keeptime;
};
#define SW_MOJING_CONTROL__CLOUD_STORAGE_INFO_CHANGE_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__cloud_storage_info_change_notify__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


struct  _SwMojingControl__Pong
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
};
#define SW_MOJING_CONTROL__PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__pong__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__RegisterResponseWithNonce
{
  ProtobufCMessage base;
  /*
   *响应代码
   */
  int32_t code;
  /*
   *响应消息
   */
  char *message;
  /*
   *验证随机数
   */
  char *nonce;
};
#define SW_MOJING_CONTROL__REGISTER_RESPONSE_WITH_NONCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__register_response_with_nonce__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__GetCloudStorageAddrRequest
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *云存类型(1:全天存储,2:动态存储)
   */
  char *cloudstoragetype;
  /*
   *码流类型(0:主码流,1:辅码流,2:第三码流)
   */
  int32_t streamtype;
  /*
   *动态存储使用-预存时间(秒) 0-10
   */
  int32_t prestoragetime;
  /*
   *动态存储使用-存储持续时间(秒)30-300
   */
  int32_t keeptime;
  /*
   *RTP/AVP/TCP PS/90000
   */
  char *streamdesc;
  /*
   *开始时间
   */
  int64_t starttime;
};
#define SW_MOJING_CONTROL__GET_CLOUD_STORAGE_ADDR_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_cloud_storage_addr_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, 0 }


struct  _SwMojingControl__CloudStorageEndNotify
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *任务ID
   */
  char *taskid;
  /*
   *开始时间
   */
  int64_t starttime;
  /*
   *结束时间
   */
  int64_t endtime;
};
#define SW_MOJING_CONTROL__CLOUD_STORAGE_END_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__cloud_storage_end_notify__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  _SwMojingControl__GetCloudStorageInfoRequest
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *请求时间
   */
  int64_t time;
};
#define SW_MOJING_CONTROL__GET_CLOUD_STORAGE_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_cloud_storage_info_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _SwMojingControl__GetCloudStorageInfoResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
  /*
   *云存类型(0:不云存,1:全天存储,2:动态存储)
   */
  int32_t cloudstoragetype;
  /*
   *码流类型(0:主码流,1:辅码流,2:第三码流)
   */
  int32_t streamtype;
  /*
   *动态存储使用-预存时间(秒) 0-10
   */
  int32_t prestoragetime;
  /*
   *动态存储使用-存储持续时间(秒)30-300
   */
  int32_t keeptime;
};
#define SW_MOJING_CONTROL__GET_CLOUD_STORAGE_INFO_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_cloud_storage_info_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


struct  _SwMojingControl__RegisterRequest
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *注册时间戳
   */
  int64_t registertime;
};
#define SW_MOJING_CONTROL__REGISTER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__register_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _SwMojingControl__DeviceUpdateRequest
{
  ProtobufCMessage base;
  /*
   *更新类型(0:固件;1:软件)
   */
  int32_t updatetype;
  /*
   *文件存放路径
   */
  char *wareurl;
  /*
   *文件版本
   */
  char *wareversion;
  /*
   *文件MD5值
   */
  char *waremd5;
  /*
   *本次升级任务ID
   */
  char *taskid;
};
#define SW_MOJING_CONTROL__DEVICE_UPDATE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__device_update_request__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__DeviceUpdateNotify
{
  ProtobufCMessage base;
  /*
   *更新类型(0:固件;1:软件)
   */
  int32_t updatetype;
  /*
   *升级任务ID
   */
  char *taskid;
  /*
   *文件版本
   */
  char *wareversion;
  /*
   *文件MD5值
   */
  char *waremd5;
  /*
   *升级时间
   */
  int64_t updatetime;
};
#define SW_MOJING_CONTROL__DEVICE_UPDATE_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__device_update_notify__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  _SwMojingControl__Ping
{
  ProtobufCMessage base;
  /*
   *当前时间
   */
  int64_t time;
};
#define SW_MOJING_CONTROL__PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__ping__descriptor) \
    , 0 }


struct  _SwMojingControl__FromatSDCardRequest
{
  ProtobufCMessage base;
  /*
   *Unix时间-东八区
   */
  int32_t date;
};
#define SW_MOJING_CONTROL__FROMAT_SDCARD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__fromat_sdcard_request__descriptor) \
    , 0 }


struct  _SwMojingControl__RegisterResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
};
#define SW_MOJING_CONTROL__REGISTER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__register_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__GetSDCardInfoRequest
{
  ProtobufCMessage base;
  /*
   *Unix时间-东八区
   */
  size_t n_date;
  int64_t *date;
};
#define SW_MOJING_CONTROL__GET_SDCARD_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_sdcard_info_request__descriptor) \
    , 0,NULL }


struct  _SwMojingControl__FromatSDCardStatNotify
{
  ProtobufCMessage base;
  /*
   *格式化状态   200:格式化完成   400:格式化错误
   */
  int32_t fromatsdcardstat;
  /*
   *响应代码;
   */
  char *message;
};
#define SW_MOJING_CONTROL__FROMAT_SDCARD_STAT_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__fromat_sdcard_stat_notify__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__DownLoadStatRequest
{
  ProtobufCMessage base;
  /*
   *下载状态  200：成功   4xx：失败
   */
  int32_t downloadstat;
  /*
   *描述
   */
  char *message;
};
#define SW_MOJING_CONTROL__DOWN_LOAD_STAT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__down_load_stat_request__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__UploadDeviceInfoResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
};
#define SW_MOJING_CONTROL__UPLOAD_DEVICE_INFO_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__upload_device_info_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__DeviceUpdateResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应消息
   */
  char *message;
};
#define SW_MOJING_CONTROL__DEVICE_UPDATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__device_update_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__RegisterRequestWithAuth
{
  ProtobufCMessage base;
  /*
   *设备ID
   */
  char *deviceid;
  /*
   *注册时间
   */
  int64_t registertime;
  /*
   *验证信息
   */
  char *auth;
  /*
   *心跳间隔时间
   */
  int32_t pingspan;
};
#define SW_MOJING_CONTROL__REGISTER_REQUEST_WITH_AUTH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__register_request_with_auth__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0 }


struct  _SwMojingControl__GetSDCardInfoResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
  /*
   *0无卡;1有卡未初始化;3有卡已初始化
   */
  int32_t sdstat;
  /*
   *单位(GB)
   */
  int32_t sdcardsize;
  /*
   *可用空间(MB)
   */
  int32_t sdcardavailablesize;
  /*
   *单位(MB)
   */
  int32_t sdcardusedsize;
};
#define SW_MOJING_CONTROL__GET_SDCARD_INFO_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_sdcard_info_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


struct  _SwMojingControl__OperateResponse
{
  ProtobufCMessage base;
  /*
   *响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
};
#define SW_MOJING_CONTROL__OPERATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__operate_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _SwMojingControl__GetCloudStorageAddrResponse
{
  ProtobufCMessage base;
  /*
   *Code响应消息
   */
  int32_t code;
  /*
   *响应代码
   */
  char *message;
  /*
   *RTP SSRC
   */
  int32_t ssrc;
  /*
   *云存服务IP
   */
  char *addrip;
  /*
   *云存服务端口
   */
  int32_t addrport;
  /*
   *传输类型(0:TCP,1:HTTP,2:TCP+TLS,3:HTTPS)
   */
  int32_t transtype;
  /*
   *任务ID
   */
  char *taskid;
};
#define SW_MOJING_CONTROL__GET_CLOUD_STORAGE_ADDR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sw_mojing_control__get_cloud_storage_addr_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


/* SwMojingControl__UploadDeviceInfoRequest methods */
void   sw_mojing_control__upload_device_info_request__init
                     (SwMojingControl__UploadDeviceInfoRequest         *message);
size_t sw_mojing_control__upload_device_info_request__get_packed_size
                     (const SwMojingControl__UploadDeviceInfoRequest   *message);
size_t sw_mojing_control__upload_device_info_request__pack
                     (const SwMojingControl__UploadDeviceInfoRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__upload_device_info_request__pack_to_buffer
                     (const SwMojingControl__UploadDeviceInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__UploadDeviceInfoRequest *
       sw_mojing_control__upload_device_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__upload_device_info_request__free_unpacked
                     (SwMojingControl__UploadDeviceInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__CloudStorageInfoChangeNotify methods */
void   sw_mojing_control__cloud_storage_info_change_notify__init
                     (SwMojingControl__CloudStorageInfoChangeNotify         *message);
size_t sw_mojing_control__cloud_storage_info_change_notify__get_packed_size
                     (const SwMojingControl__CloudStorageInfoChangeNotify   *message);
size_t sw_mojing_control__cloud_storage_info_change_notify__pack
                     (const SwMojingControl__CloudStorageInfoChangeNotify   *message,
                      uint8_t             *out);
size_t sw_mojing_control__cloud_storage_info_change_notify__pack_to_buffer
                     (const SwMojingControl__CloudStorageInfoChangeNotify   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__CloudStorageInfoChangeNotify *
       sw_mojing_control__cloud_storage_info_change_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__cloud_storage_info_change_notify__free_unpacked
                     (SwMojingControl__CloudStorageInfoChangeNotify *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__Pong methods */
void   sw_mojing_control__pong__init
                     (SwMojingControl__Pong         *message);
size_t sw_mojing_control__pong__get_packed_size
                     (const SwMojingControl__Pong   *message);
size_t sw_mojing_control__pong__pack
                     (const SwMojingControl__Pong   *message,
                      uint8_t             *out);
size_t sw_mojing_control__pong__pack_to_buffer
                     (const SwMojingControl__Pong   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__Pong *
       sw_mojing_control__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__pong__free_unpacked
                     (SwMojingControl__Pong *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__RegisterResponseWithNonce methods */
void   sw_mojing_control__register_response_with_nonce__init
                     (SwMojingControl__RegisterResponseWithNonce         *message);
size_t sw_mojing_control__register_response_with_nonce__get_packed_size
                     (const SwMojingControl__RegisterResponseWithNonce   *message);
size_t sw_mojing_control__register_response_with_nonce__pack
                     (const SwMojingControl__RegisterResponseWithNonce   *message,
                      uint8_t             *out);
size_t sw_mojing_control__register_response_with_nonce__pack_to_buffer
                     (const SwMojingControl__RegisterResponseWithNonce   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__RegisterResponseWithNonce *
       sw_mojing_control__register_response_with_nonce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__register_response_with_nonce__free_unpacked
                     (SwMojingControl__RegisterResponseWithNonce *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetCloudStorageAddrRequest methods */
void   sw_mojing_control__get_cloud_storage_addr_request__init
                     (SwMojingControl__GetCloudStorageAddrRequest         *message);
size_t sw_mojing_control__get_cloud_storage_addr_request__get_packed_size
                     (const SwMojingControl__GetCloudStorageAddrRequest   *message);
size_t sw_mojing_control__get_cloud_storage_addr_request__pack
                     (const SwMojingControl__GetCloudStorageAddrRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_cloud_storage_addr_request__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageAddrRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetCloudStorageAddrRequest *
       sw_mojing_control__get_cloud_storage_addr_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_cloud_storage_addr_request__free_unpacked
                     (SwMojingControl__GetCloudStorageAddrRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__CloudStorageEndNotify methods */
void   sw_mojing_control__cloud_storage_end_notify__init
                     (SwMojingControl__CloudStorageEndNotify         *message);
size_t sw_mojing_control__cloud_storage_end_notify__get_packed_size
                     (const SwMojingControl__CloudStorageEndNotify   *message);
size_t sw_mojing_control__cloud_storage_end_notify__pack
                     (const SwMojingControl__CloudStorageEndNotify   *message,
                      uint8_t             *out);
size_t sw_mojing_control__cloud_storage_end_notify__pack_to_buffer
                     (const SwMojingControl__CloudStorageEndNotify   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__CloudStorageEndNotify *
       sw_mojing_control__cloud_storage_end_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__cloud_storage_end_notify__free_unpacked
                     (SwMojingControl__CloudStorageEndNotify *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetCloudStorageInfoRequest methods */
void   sw_mojing_control__get_cloud_storage_info_request__init
                     (SwMojingControl__GetCloudStorageInfoRequest         *message);
size_t sw_mojing_control__get_cloud_storage_info_request__get_packed_size
                     (const SwMojingControl__GetCloudStorageInfoRequest   *message);
size_t sw_mojing_control__get_cloud_storage_info_request__pack
                     (const SwMojingControl__GetCloudStorageInfoRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_cloud_storage_info_request__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetCloudStorageInfoRequest *
       sw_mojing_control__get_cloud_storage_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_cloud_storage_info_request__free_unpacked
                     (SwMojingControl__GetCloudStorageInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetCloudStorageInfoResponse methods */
void   sw_mojing_control__get_cloud_storage_info_response__init
                     (SwMojingControl__GetCloudStorageInfoResponse         *message);
size_t sw_mojing_control__get_cloud_storage_info_response__get_packed_size
                     (const SwMojingControl__GetCloudStorageInfoResponse   *message);
size_t sw_mojing_control__get_cloud_storage_info_response__pack
                     (const SwMojingControl__GetCloudStorageInfoResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_cloud_storage_info_response__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetCloudStorageInfoResponse *
       sw_mojing_control__get_cloud_storage_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_cloud_storage_info_response__free_unpacked
                     (SwMojingControl__GetCloudStorageInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__RegisterRequest methods */
void   sw_mojing_control__register_request__init
                     (SwMojingControl__RegisterRequest         *message);
size_t sw_mojing_control__register_request__get_packed_size
                     (const SwMojingControl__RegisterRequest   *message);
size_t sw_mojing_control__register_request__pack
                     (const SwMojingControl__RegisterRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__register_request__pack_to_buffer
                     (const SwMojingControl__RegisterRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__RegisterRequest *
       sw_mojing_control__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__register_request__free_unpacked
                     (SwMojingControl__RegisterRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__DeviceUpdateRequest methods */
void   sw_mojing_control__device_update_request__init
                     (SwMojingControl__DeviceUpdateRequest         *message);
size_t sw_mojing_control__device_update_request__get_packed_size
                     (const SwMojingControl__DeviceUpdateRequest   *message);
size_t sw_mojing_control__device_update_request__pack
                     (const SwMojingControl__DeviceUpdateRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__device_update_request__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__DeviceUpdateRequest *
       sw_mojing_control__device_update_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__device_update_request__free_unpacked
                     (SwMojingControl__DeviceUpdateRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__DeviceUpdateNotify methods */
void   sw_mojing_control__device_update_notify__init
                     (SwMojingControl__DeviceUpdateNotify         *message);
size_t sw_mojing_control__device_update_notify__get_packed_size
                     (const SwMojingControl__DeviceUpdateNotify   *message);
size_t sw_mojing_control__device_update_notify__pack
                     (const SwMojingControl__DeviceUpdateNotify   *message,
                      uint8_t             *out);
size_t sw_mojing_control__device_update_notify__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateNotify   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__DeviceUpdateNotify *
       sw_mojing_control__device_update_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__device_update_notify__free_unpacked
                     (SwMojingControl__DeviceUpdateNotify *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__Ping methods */
void   sw_mojing_control__ping__init
                     (SwMojingControl__Ping         *message);
size_t sw_mojing_control__ping__get_packed_size
                     (const SwMojingControl__Ping   *message);
size_t sw_mojing_control__ping__pack
                     (const SwMojingControl__Ping   *message,
                      uint8_t             *out);
size_t sw_mojing_control__ping__pack_to_buffer
                     (const SwMojingControl__Ping   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__Ping *
       sw_mojing_control__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__ping__free_unpacked
                     (SwMojingControl__Ping *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__FromatSDCardRequest methods */
void   sw_mojing_control__fromat_sdcard_request__init
                     (SwMojingControl__FromatSDCardRequest         *message);
size_t sw_mojing_control__fromat_sdcard_request__get_packed_size
                     (const SwMojingControl__FromatSDCardRequest   *message);
size_t sw_mojing_control__fromat_sdcard_request__pack
                     (const SwMojingControl__FromatSDCardRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__fromat_sdcard_request__pack_to_buffer
                     (const SwMojingControl__FromatSDCardRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__FromatSDCardRequest *
       sw_mojing_control__fromat_sdcard_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__fromat_sdcard_request__free_unpacked
                     (SwMojingControl__FromatSDCardRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__RegisterResponse methods */
void   sw_mojing_control__register_response__init
                     (SwMojingControl__RegisterResponse         *message);
size_t sw_mojing_control__register_response__get_packed_size
                     (const SwMojingControl__RegisterResponse   *message);
size_t sw_mojing_control__register_response__pack
                     (const SwMojingControl__RegisterResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__register_response__pack_to_buffer
                     (const SwMojingControl__RegisterResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__RegisterResponse *
       sw_mojing_control__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__register_response__free_unpacked
                     (SwMojingControl__RegisterResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetSDCardInfoRequest methods */
void   sw_mojing_control__get_sdcard_info_request__init
                     (SwMojingControl__GetSDCardInfoRequest         *message);
size_t sw_mojing_control__get_sdcard_info_request__get_packed_size
                     (const SwMojingControl__GetSDCardInfoRequest   *message);
size_t sw_mojing_control__get_sdcard_info_request__pack
                     (const SwMojingControl__GetSDCardInfoRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_sdcard_info_request__pack_to_buffer
                     (const SwMojingControl__GetSDCardInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetSDCardInfoRequest *
       sw_mojing_control__get_sdcard_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_sdcard_info_request__free_unpacked
                     (SwMojingControl__GetSDCardInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__FromatSDCardStatNotify methods */
void   sw_mojing_control__fromat_sdcard_stat_notify__init
                     (SwMojingControl__FromatSDCardStatNotify         *message);
size_t sw_mojing_control__fromat_sdcard_stat_notify__get_packed_size
                     (const SwMojingControl__FromatSDCardStatNotify   *message);
size_t sw_mojing_control__fromat_sdcard_stat_notify__pack
                     (const SwMojingControl__FromatSDCardStatNotify   *message,
                      uint8_t             *out);
size_t sw_mojing_control__fromat_sdcard_stat_notify__pack_to_buffer
                     (const SwMojingControl__FromatSDCardStatNotify   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__FromatSDCardStatNotify *
       sw_mojing_control__fromat_sdcard_stat_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__fromat_sdcard_stat_notify__free_unpacked
                     (SwMojingControl__FromatSDCardStatNotify *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__DownLoadStatRequest methods */
void   sw_mojing_control__down_load_stat_request__init
                     (SwMojingControl__DownLoadStatRequest         *message);
size_t sw_mojing_control__down_load_stat_request__get_packed_size
                     (const SwMojingControl__DownLoadStatRequest   *message);
size_t sw_mojing_control__down_load_stat_request__pack
                     (const SwMojingControl__DownLoadStatRequest   *message,
                      uint8_t             *out);
size_t sw_mojing_control__down_load_stat_request__pack_to_buffer
                     (const SwMojingControl__DownLoadStatRequest   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__DownLoadStatRequest *
       sw_mojing_control__down_load_stat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__down_load_stat_request__free_unpacked
                     (SwMojingControl__DownLoadStatRequest *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__UploadDeviceInfoResponse methods */
void   sw_mojing_control__upload_device_info_response__init
                     (SwMojingControl__UploadDeviceInfoResponse         *message);
size_t sw_mojing_control__upload_device_info_response__get_packed_size
                     (const SwMojingControl__UploadDeviceInfoResponse   *message);
size_t sw_mojing_control__upload_device_info_response__pack
                     (const SwMojingControl__UploadDeviceInfoResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__upload_device_info_response__pack_to_buffer
                     (const SwMojingControl__UploadDeviceInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__UploadDeviceInfoResponse *
       sw_mojing_control__upload_device_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__upload_device_info_response__free_unpacked
                     (SwMojingControl__UploadDeviceInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__DeviceUpdateResponse methods */
void   sw_mojing_control__device_update_response__init
                     (SwMojingControl__DeviceUpdateResponse         *message);
size_t sw_mojing_control__device_update_response__get_packed_size
                     (const SwMojingControl__DeviceUpdateResponse   *message);
size_t sw_mojing_control__device_update_response__pack
                     (const SwMojingControl__DeviceUpdateResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__device_update_response__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__DeviceUpdateResponse *
       sw_mojing_control__device_update_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__device_update_response__free_unpacked
                     (SwMojingControl__DeviceUpdateResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__RegisterRequestWithAuth methods */
void   sw_mojing_control__register_request_with_auth__init
                     (SwMojingControl__RegisterRequestWithAuth         *message);
size_t sw_mojing_control__register_request_with_auth__get_packed_size
                     (const SwMojingControl__RegisterRequestWithAuth   *message);
size_t sw_mojing_control__register_request_with_auth__pack
                     (const SwMojingControl__RegisterRequestWithAuth   *message,
                      uint8_t             *out);
size_t sw_mojing_control__register_request_with_auth__pack_to_buffer
                     (const SwMojingControl__RegisterRequestWithAuth   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__RegisterRequestWithAuth *
       sw_mojing_control__register_request_with_auth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__register_request_with_auth__free_unpacked
                     (SwMojingControl__RegisterRequestWithAuth *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetSDCardInfoResponse methods */
void   sw_mojing_control__get_sdcard_info_response__init
                     (SwMojingControl__GetSDCardInfoResponse         *message);
size_t sw_mojing_control__get_sdcard_info_response__get_packed_size
                     (const SwMojingControl__GetSDCardInfoResponse   *message);
size_t sw_mojing_control__get_sdcard_info_response__pack
                     (const SwMojingControl__GetSDCardInfoResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_sdcard_info_response__pack_to_buffer
                     (const SwMojingControl__GetSDCardInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetSDCardInfoResponse *
       sw_mojing_control__get_sdcard_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_sdcard_info_response__free_unpacked
                     (SwMojingControl__GetSDCardInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__OperateResponse methods */
void   sw_mojing_control__operate_response__init
                     (SwMojingControl__OperateResponse         *message);
size_t sw_mojing_control__operate_response__get_packed_size
                     (const SwMojingControl__OperateResponse   *message);
size_t sw_mojing_control__operate_response__pack
                     (const SwMojingControl__OperateResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__operate_response__pack_to_buffer
                     (const SwMojingControl__OperateResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__OperateResponse *
       sw_mojing_control__operate_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__operate_response__free_unpacked
                     (SwMojingControl__OperateResponse *message,
                      ProtobufCAllocator *allocator);
/* SwMojingControl__GetCloudStorageAddrResponse methods */
void   sw_mojing_control__get_cloud_storage_addr_response__init
                     (SwMojingControl__GetCloudStorageAddrResponse         *message);
size_t sw_mojing_control__get_cloud_storage_addr_response__get_packed_size
                     (const SwMojingControl__GetCloudStorageAddrResponse   *message);
size_t sw_mojing_control__get_cloud_storage_addr_response__pack
                     (const SwMojingControl__GetCloudStorageAddrResponse   *message,
                      uint8_t             *out);
size_t sw_mojing_control__get_cloud_storage_addr_response__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageAddrResponse   *message,
                      ProtobufCBuffer     *buffer);
SwMojingControl__GetCloudStorageAddrResponse *
       sw_mojing_control__get_cloud_storage_addr_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sw_mojing_control__get_cloud_storage_addr_response__free_unpacked
                     (SwMojingControl__GetCloudStorageAddrResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SwMojingControl__UploadDeviceInfoRequest_Closure)
                 (const SwMojingControl__UploadDeviceInfoRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__CloudStorageInfoChangeNotify_Closure)
                 (const SwMojingControl__CloudStorageInfoChangeNotify *message,
                  void *closure_data);
typedef void (*SwMojingControl__Pong_Closure)
                 (const SwMojingControl__Pong *message,
                  void *closure_data);
typedef void (*SwMojingControl__RegisterResponseWithNonce_Closure)
                 (const SwMojingControl__RegisterResponseWithNonce *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetCloudStorageAddrRequest_Closure)
                 (const SwMojingControl__GetCloudStorageAddrRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__CloudStorageEndNotify_Closure)
                 (const SwMojingControl__CloudStorageEndNotify *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetCloudStorageInfoRequest_Closure)
                 (const SwMojingControl__GetCloudStorageInfoRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetCloudStorageInfoResponse_Closure)
                 (const SwMojingControl__GetCloudStorageInfoResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__RegisterRequest_Closure)
                 (const SwMojingControl__RegisterRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__DeviceUpdateRequest_Closure)
                 (const SwMojingControl__DeviceUpdateRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__DeviceUpdateNotify_Closure)
                 (const SwMojingControl__DeviceUpdateNotify *message,
                  void *closure_data);
typedef void (*SwMojingControl__Ping_Closure)
                 (const SwMojingControl__Ping *message,
                  void *closure_data);
typedef void (*SwMojingControl__FromatSDCardRequest_Closure)
                 (const SwMojingControl__FromatSDCardRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__RegisterResponse_Closure)
                 (const SwMojingControl__RegisterResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetSDCardInfoRequest_Closure)
                 (const SwMojingControl__GetSDCardInfoRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__FromatSDCardStatNotify_Closure)
                 (const SwMojingControl__FromatSDCardStatNotify *message,
                  void *closure_data);
typedef void (*SwMojingControl__DownLoadStatRequest_Closure)
                 (const SwMojingControl__DownLoadStatRequest *message,
                  void *closure_data);
typedef void (*SwMojingControl__UploadDeviceInfoResponse_Closure)
                 (const SwMojingControl__UploadDeviceInfoResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__DeviceUpdateResponse_Closure)
                 (const SwMojingControl__DeviceUpdateResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__RegisterRequestWithAuth_Closure)
                 (const SwMojingControl__RegisterRequestWithAuth *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetSDCardInfoResponse_Closure)
                 (const SwMojingControl__GetSDCardInfoResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__OperateResponse_Closure)
                 (const SwMojingControl__OperateResponse *message,
                  void *closure_data);
typedef void (*SwMojingControl__GetCloudStorageAddrResponse_Closure)
                 (const SwMojingControl__GetCloudStorageAddrResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sw_mojing_control__upload_device_info_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__cloud_storage_info_change_notify__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__pong__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__register_response_with_nonce__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_addr_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__cloud_storage_end_notify__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_info_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_info_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__register_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__device_update_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__device_update_notify__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__ping__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__fromat_sdcard_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__register_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_sdcard_info_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__fromat_sdcard_stat_notify__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__down_load_stat_request__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__upload_device_info_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__device_update_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__register_request_with_auth__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_sdcard_info_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__operate_response__descriptor;
extern const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_addr_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mojing_5fcontrol_2eproto__INCLUDED */
