/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mojing_control.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mojing_control.pb-c.h"
void   sw_mojing_control__upload_device_info_request__init
                     (SwMojingControl__UploadDeviceInfoRequest         *message)
{
  static const SwMojingControl__UploadDeviceInfoRequest init_value = SW_MOJING_CONTROL__UPLOAD_DEVICE_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__upload_device_info_request__get_packed_size
                     (const SwMojingControl__UploadDeviceInfoRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__upload_device_info_request__pack
                     (const SwMojingControl__UploadDeviceInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__upload_device_info_request__pack_to_buffer
                     (const SwMojingControl__UploadDeviceInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__UploadDeviceInfoRequest *
       sw_mojing_control__upload_device_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__UploadDeviceInfoRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__upload_device_info_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__upload_device_info_request__free_unpacked
                     (SwMojingControl__UploadDeviceInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__cloud_storage_info_change_notify__init
                     (SwMojingControl__CloudStorageInfoChangeNotify         *message)
{
  static const SwMojingControl__CloudStorageInfoChangeNotify init_value = SW_MOJING_CONTROL__CLOUD_STORAGE_INFO_CHANGE_NOTIFY__INIT;
  *message = init_value;
}
size_t sw_mojing_control__cloud_storage_info_change_notify__get_packed_size
                     (const SwMojingControl__CloudStorageInfoChangeNotify *message)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_info_change_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__cloud_storage_info_change_notify__pack
                     (const SwMojingControl__CloudStorageInfoChangeNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_info_change_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__cloud_storage_info_change_notify__pack_to_buffer
                     (const SwMojingControl__CloudStorageInfoChangeNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_info_change_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__CloudStorageInfoChangeNotify *
       sw_mojing_control__cloud_storage_info_change_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__CloudStorageInfoChangeNotify *)
     protobuf_c_message_unpack (&sw_mojing_control__cloud_storage_info_change_notify__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__cloud_storage_info_change_notify__free_unpacked
                     (SwMojingControl__CloudStorageInfoChangeNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_info_change_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__pong__init
                     (SwMojingControl__Pong         *message)
{
  static const SwMojingControl__Pong init_value = SW_MOJING_CONTROL__PONG__INIT;
  *message = init_value;
}
size_t sw_mojing_control__pong__get_packed_size
                     (const SwMojingControl__Pong *message)
{
  assert(message->base.descriptor == &sw_mojing_control__pong__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__pong__pack
                     (const SwMojingControl__Pong *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__pong__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__pong__pack_to_buffer
                     (const SwMojingControl__Pong *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__pong__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__Pong *
       sw_mojing_control__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__Pong *)
     protobuf_c_message_unpack (&sw_mojing_control__pong__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__pong__free_unpacked
                     (SwMojingControl__Pong *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__pong__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__register_response_with_nonce__init
                     (SwMojingControl__RegisterResponseWithNonce         *message)
{
  static const SwMojingControl__RegisterResponseWithNonce init_value = SW_MOJING_CONTROL__REGISTER_RESPONSE_WITH_NONCE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__register_response_with_nonce__get_packed_size
                     (const SwMojingControl__RegisterResponseWithNonce *message)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response_with_nonce__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__register_response_with_nonce__pack
                     (const SwMojingControl__RegisterResponseWithNonce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response_with_nonce__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__register_response_with_nonce__pack_to_buffer
                     (const SwMojingControl__RegisterResponseWithNonce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response_with_nonce__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__RegisterResponseWithNonce *
       sw_mojing_control__register_response_with_nonce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__RegisterResponseWithNonce *)
     protobuf_c_message_unpack (&sw_mojing_control__register_response_with_nonce__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__register_response_with_nonce__free_unpacked
                     (SwMojingControl__RegisterResponseWithNonce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__register_response_with_nonce__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_cloud_storage_addr_request__init
                     (SwMojingControl__GetCloudStorageAddrRequest         *message)
{
  static const SwMojingControl__GetCloudStorageAddrRequest init_value = SW_MOJING_CONTROL__GET_CLOUD_STORAGE_ADDR_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_cloud_storage_addr_request__get_packed_size
                     (const SwMojingControl__GetCloudStorageAddrRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_cloud_storage_addr_request__pack
                     (const SwMojingControl__GetCloudStorageAddrRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_cloud_storage_addr_request__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageAddrRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetCloudStorageAddrRequest *
       sw_mojing_control__get_cloud_storage_addr_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetCloudStorageAddrRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__get_cloud_storage_addr_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_cloud_storage_addr_request__free_unpacked
                     (SwMojingControl__GetCloudStorageAddrRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__cloud_storage_end_notify__init
                     (SwMojingControl__CloudStorageEndNotify         *message)
{
  static const SwMojingControl__CloudStorageEndNotify init_value = SW_MOJING_CONTROL__CLOUD_STORAGE_END_NOTIFY__INIT;
  *message = init_value;
}
size_t sw_mojing_control__cloud_storage_end_notify__get_packed_size
                     (const SwMojingControl__CloudStorageEndNotify *message)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_end_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__cloud_storage_end_notify__pack
                     (const SwMojingControl__CloudStorageEndNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_end_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__cloud_storage_end_notify__pack_to_buffer
                     (const SwMojingControl__CloudStorageEndNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_end_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__CloudStorageEndNotify *
       sw_mojing_control__cloud_storage_end_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__CloudStorageEndNotify *)
     protobuf_c_message_unpack (&sw_mojing_control__cloud_storage_end_notify__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__cloud_storage_end_notify__free_unpacked
                     (SwMojingControl__CloudStorageEndNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__cloud_storage_end_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_cloud_storage_info_request__init
                     (SwMojingControl__GetCloudStorageInfoRequest         *message)
{
  static const SwMojingControl__GetCloudStorageInfoRequest init_value = SW_MOJING_CONTROL__GET_CLOUD_STORAGE_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_cloud_storage_info_request__get_packed_size
                     (const SwMojingControl__GetCloudStorageInfoRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_cloud_storage_info_request__pack
                     (const SwMojingControl__GetCloudStorageInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_cloud_storage_info_request__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetCloudStorageInfoRequest *
       sw_mojing_control__get_cloud_storage_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetCloudStorageInfoRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__get_cloud_storage_info_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_cloud_storage_info_request__free_unpacked
                     (SwMojingControl__GetCloudStorageInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_cloud_storage_info_response__init
                     (SwMojingControl__GetCloudStorageInfoResponse         *message)
{
  static const SwMojingControl__GetCloudStorageInfoResponse init_value = SW_MOJING_CONTROL__GET_CLOUD_STORAGE_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_cloud_storage_info_response__get_packed_size
                     (const SwMojingControl__GetCloudStorageInfoResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_cloud_storage_info_response__pack
                     (const SwMojingControl__GetCloudStorageInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_cloud_storage_info_response__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetCloudStorageInfoResponse *
       sw_mojing_control__get_cloud_storage_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetCloudStorageInfoResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__get_cloud_storage_info_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_cloud_storage_info_response__free_unpacked
                     (SwMojingControl__GetCloudStorageInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__register_request__init
                     (SwMojingControl__RegisterRequest         *message)
{
  static const SwMojingControl__RegisterRequest init_value = SW_MOJING_CONTROL__REGISTER_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__register_request__get_packed_size
                     (const SwMojingControl__RegisterRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__register_request__pack
                     (const SwMojingControl__RegisterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__register_request__pack_to_buffer
                     (const SwMojingControl__RegisterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__RegisterRequest *
       sw_mojing_control__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__RegisterRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__register_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__register_request__free_unpacked
                     (SwMojingControl__RegisterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__register_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__device_update_request__init
                     (SwMojingControl__DeviceUpdateRequest         *message)
{
  static const SwMojingControl__DeviceUpdateRequest init_value = SW_MOJING_CONTROL__DEVICE_UPDATE_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__device_update_request__get_packed_size
                     (const SwMojingControl__DeviceUpdateRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__device_update_request__pack
                     (const SwMojingControl__DeviceUpdateRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__device_update_request__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__DeviceUpdateRequest *
       sw_mojing_control__device_update_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__DeviceUpdateRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__device_update_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__device_update_request__free_unpacked
                     (SwMojingControl__DeviceUpdateRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__device_update_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__device_update_notify__init
                     (SwMojingControl__DeviceUpdateNotify         *message)
{
  static const SwMojingControl__DeviceUpdateNotify init_value = SW_MOJING_CONTROL__DEVICE_UPDATE_NOTIFY__INIT;
  *message = init_value;
}
size_t sw_mojing_control__device_update_notify__get_packed_size
                     (const SwMojingControl__DeviceUpdateNotify *message)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__device_update_notify__pack
                     (const SwMojingControl__DeviceUpdateNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__device_update_notify__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__DeviceUpdateNotify *
       sw_mojing_control__device_update_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__DeviceUpdateNotify *)
     protobuf_c_message_unpack (&sw_mojing_control__device_update_notify__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__device_update_notify__free_unpacked
                     (SwMojingControl__DeviceUpdateNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__device_update_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__ping__init
                     (SwMojingControl__Ping         *message)
{
  static const SwMojingControl__Ping init_value = SW_MOJING_CONTROL__PING__INIT;
  *message = init_value;
}
size_t sw_mojing_control__ping__get_packed_size
                     (const SwMojingControl__Ping *message)
{
  assert(message->base.descriptor == &sw_mojing_control__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__ping__pack
                     (const SwMojingControl__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__ping__pack_to_buffer
                     (const SwMojingControl__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__Ping *
       sw_mojing_control__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__Ping *)
     protobuf_c_message_unpack (&sw_mojing_control__ping__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__ping__free_unpacked
                     (SwMojingControl__Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__fromat_sdcard_request__init
                     (SwMojingControl__FromatSDCardRequest         *message)
{
  static const SwMojingControl__FromatSDCardRequest init_value = SW_MOJING_CONTROL__FROMAT_SDCARD_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__fromat_sdcard_request__get_packed_size
                     (const SwMojingControl__FromatSDCardRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__fromat_sdcard_request__pack
                     (const SwMojingControl__FromatSDCardRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__fromat_sdcard_request__pack_to_buffer
                     (const SwMojingControl__FromatSDCardRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__FromatSDCardRequest *
       sw_mojing_control__fromat_sdcard_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__FromatSDCardRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__fromat_sdcard_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__fromat_sdcard_request__free_unpacked
                     (SwMojingControl__FromatSDCardRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__register_response__init
                     (SwMojingControl__RegisterResponse         *message)
{
  static const SwMojingControl__RegisterResponse init_value = SW_MOJING_CONTROL__REGISTER_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__register_response__get_packed_size
                     (const SwMojingControl__RegisterResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__register_response__pack
                     (const SwMojingControl__RegisterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__register_response__pack_to_buffer
                     (const SwMojingControl__RegisterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__register_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__RegisterResponse *
       sw_mojing_control__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__RegisterResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__register_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__register_response__free_unpacked
                     (SwMojingControl__RegisterResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__register_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_sdcard_info_request__init
                     (SwMojingControl__GetSDCardInfoRequest         *message)
{
  static const SwMojingControl__GetSDCardInfoRequest init_value = SW_MOJING_CONTROL__GET_SDCARD_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_sdcard_info_request__get_packed_size
                     (const SwMojingControl__GetSDCardInfoRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_sdcard_info_request__pack
                     (const SwMojingControl__GetSDCardInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_sdcard_info_request__pack_to_buffer
                     (const SwMojingControl__GetSDCardInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetSDCardInfoRequest *
       sw_mojing_control__get_sdcard_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetSDCardInfoRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__get_sdcard_info_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_sdcard_info_request__free_unpacked
                     (SwMojingControl__GetSDCardInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__fromat_sdcard_stat_notify__init
                     (SwMojingControl__FromatSDCardStatNotify         *message)
{
  static const SwMojingControl__FromatSDCardStatNotify init_value = SW_MOJING_CONTROL__FROMAT_SDCARD_STAT_NOTIFY__INIT;
  *message = init_value;
}
size_t sw_mojing_control__fromat_sdcard_stat_notify__get_packed_size
                     (const SwMojingControl__FromatSDCardStatNotify *message)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_stat_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__fromat_sdcard_stat_notify__pack
                     (const SwMojingControl__FromatSDCardStatNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_stat_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__fromat_sdcard_stat_notify__pack_to_buffer
                     (const SwMojingControl__FromatSDCardStatNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_stat_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__FromatSDCardStatNotify *
       sw_mojing_control__fromat_sdcard_stat_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__FromatSDCardStatNotify *)
     protobuf_c_message_unpack (&sw_mojing_control__fromat_sdcard_stat_notify__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__fromat_sdcard_stat_notify__free_unpacked
                     (SwMojingControl__FromatSDCardStatNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__fromat_sdcard_stat_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__down_load_stat_request__init
                     (SwMojingControl__DownLoadStatRequest         *message)
{
  static const SwMojingControl__DownLoadStatRequest init_value = SW_MOJING_CONTROL__DOWN_LOAD_STAT_REQUEST__INIT;
  *message = init_value;
}
size_t sw_mojing_control__down_load_stat_request__get_packed_size
                     (const SwMojingControl__DownLoadStatRequest *message)
{
  assert(message->base.descriptor == &sw_mojing_control__down_load_stat_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__down_load_stat_request__pack
                     (const SwMojingControl__DownLoadStatRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__down_load_stat_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__down_load_stat_request__pack_to_buffer
                     (const SwMojingControl__DownLoadStatRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__down_load_stat_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__DownLoadStatRequest *
       sw_mojing_control__down_load_stat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__DownLoadStatRequest *)
     protobuf_c_message_unpack (&sw_mojing_control__down_load_stat_request__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__down_load_stat_request__free_unpacked
                     (SwMojingControl__DownLoadStatRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__down_load_stat_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__upload_device_info_response__init
                     (SwMojingControl__UploadDeviceInfoResponse         *message)
{
  static const SwMojingControl__UploadDeviceInfoResponse init_value = SW_MOJING_CONTROL__UPLOAD_DEVICE_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__upload_device_info_response__get_packed_size
                     (const SwMojingControl__UploadDeviceInfoResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__upload_device_info_response__pack
                     (const SwMojingControl__UploadDeviceInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__upload_device_info_response__pack_to_buffer
                     (const SwMojingControl__UploadDeviceInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__UploadDeviceInfoResponse *
       sw_mojing_control__upload_device_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__UploadDeviceInfoResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__upload_device_info_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__upload_device_info_response__free_unpacked
                     (SwMojingControl__UploadDeviceInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__upload_device_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__device_update_response__init
                     (SwMojingControl__DeviceUpdateResponse         *message)
{
  static const SwMojingControl__DeviceUpdateResponse init_value = SW_MOJING_CONTROL__DEVICE_UPDATE_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__device_update_response__get_packed_size
                     (const SwMojingControl__DeviceUpdateResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__device_update_response__pack
                     (const SwMojingControl__DeviceUpdateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__device_update_response__pack_to_buffer
                     (const SwMojingControl__DeviceUpdateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__device_update_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__DeviceUpdateResponse *
       sw_mojing_control__device_update_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__DeviceUpdateResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__device_update_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__device_update_response__free_unpacked
                     (SwMojingControl__DeviceUpdateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__device_update_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__register_request_with_auth__init
                     (SwMojingControl__RegisterRequestWithAuth         *message)
{
  static const SwMojingControl__RegisterRequestWithAuth init_value = SW_MOJING_CONTROL__REGISTER_REQUEST_WITH_AUTH__INIT;
  *message = init_value;
}
size_t sw_mojing_control__register_request_with_auth__get_packed_size
                     (const SwMojingControl__RegisterRequestWithAuth *message)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request_with_auth__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__register_request_with_auth__pack
                     (const SwMojingControl__RegisterRequestWithAuth *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request_with_auth__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__register_request_with_auth__pack_to_buffer
                     (const SwMojingControl__RegisterRequestWithAuth *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__register_request_with_auth__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__RegisterRequestWithAuth *
       sw_mojing_control__register_request_with_auth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__RegisterRequestWithAuth *)
     protobuf_c_message_unpack (&sw_mojing_control__register_request_with_auth__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__register_request_with_auth__free_unpacked
                     (SwMojingControl__RegisterRequestWithAuth *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__register_request_with_auth__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_sdcard_info_response__init
                     (SwMojingControl__GetSDCardInfoResponse         *message)
{
  static const SwMojingControl__GetSDCardInfoResponse init_value = SW_MOJING_CONTROL__GET_SDCARD_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_sdcard_info_response__get_packed_size
                     (const SwMojingControl__GetSDCardInfoResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_sdcard_info_response__pack
                     (const SwMojingControl__GetSDCardInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_sdcard_info_response__pack_to_buffer
                     (const SwMojingControl__GetSDCardInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetSDCardInfoResponse *
       sw_mojing_control__get_sdcard_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetSDCardInfoResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__get_sdcard_info_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_sdcard_info_response__free_unpacked
                     (SwMojingControl__GetSDCardInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_sdcard_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__operate_response__init
                     (SwMojingControl__OperateResponse         *message)
{
  static const SwMojingControl__OperateResponse init_value = SW_MOJING_CONTROL__OPERATE_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__operate_response__get_packed_size
                     (const SwMojingControl__OperateResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__operate_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__operate_response__pack
                     (const SwMojingControl__OperateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__operate_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__operate_response__pack_to_buffer
                     (const SwMojingControl__OperateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__operate_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__OperateResponse *
       sw_mojing_control__operate_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__OperateResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__operate_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__operate_response__free_unpacked
                     (SwMojingControl__OperateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__operate_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sw_mojing_control__get_cloud_storage_addr_response__init
                     (SwMojingControl__GetCloudStorageAddrResponse         *message)
{
  static const SwMojingControl__GetCloudStorageAddrResponse init_value = SW_MOJING_CONTROL__GET_CLOUD_STORAGE_ADDR_RESPONSE__INIT;
  *message = init_value;
}
size_t sw_mojing_control__get_cloud_storage_addr_response__get_packed_size
                     (const SwMojingControl__GetCloudStorageAddrResponse *message)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sw_mojing_control__get_cloud_storage_addr_response__pack
                     (const SwMojingControl__GetCloudStorageAddrResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sw_mojing_control__get_cloud_storage_addr_response__pack_to_buffer
                     (const SwMojingControl__GetCloudStorageAddrResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SwMojingControl__GetCloudStorageAddrResponse *
       sw_mojing_control__get_cloud_storage_addr_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SwMojingControl__GetCloudStorageAddrResponse *)
     protobuf_c_message_unpack (&sw_mojing_control__get_cloud_storage_addr_response__descriptor,
                                allocator, len, data);
}
void   sw_mojing_control__get_cloud_storage_addr_response__free_unpacked
                     (SwMojingControl__GetCloudStorageAddrResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sw_mojing_control__get_cloud_storage_addr_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sw_mojing_control__upload_device_info_request__field_descriptors[6] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, devicename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FirmwareVersion",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, firmwareversion),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FirmwareMD5",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, firmwaremd5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SoftwareVersion",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, softwareversion),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SoftwareMD5",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoRequest, softwaremd5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__upload_device_info_request__field_indices_by_name[] = {
  0,   /* field[0] = DeviceID */
  1,   /* field[1] = DeviceName */
  3,   /* field[3] = FirmwareMD5 */
  2,   /* field[2] = FirmwareVersion */
  5,   /* field[5] = SoftwareMD5 */
  4,   /* field[4] = SoftwareVersion */
};
static const ProtobufCIntRange sw_mojing_control__upload_device_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sw_mojing_control__upload_device_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.UploadDeviceInfoRequest",
  "UploadDeviceInfoRequest",
  "SwMojingControl__UploadDeviceInfoRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__UploadDeviceInfoRequest),
  6,
  sw_mojing_control__upload_device_info_request__field_descriptors,
  sw_mojing_control__upload_device_info_request__field_indices_by_name,
  1,  sw_mojing_control__upload_device_info_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__upload_device_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__cloud_storage_info_change_notify__field_descriptors[5] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageInfoChangeNotify, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CloudStorageType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageInfoChangeNotify, cloudstoragetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StreamType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageInfoChangeNotify, streamtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PreStorageTime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageInfoChangeNotify, prestoragetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "KeepTime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageInfoChangeNotify, keeptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__cloud_storage_info_change_notify__field_indices_by_name[] = {
  1,   /* field[1] = CloudStorageType */
  0,   /* field[0] = DeviceID */
  4,   /* field[4] = KeepTime */
  3,   /* field[3] = PreStorageTime */
  2,   /* field[2] = StreamType */
};
static const ProtobufCIntRange sw_mojing_control__cloud_storage_info_change_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sw_mojing_control__cloud_storage_info_change_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.CloudStorageInfoChangeNotify",
  "CloudStorageInfoChangeNotify",
  "SwMojingControl__CloudStorageInfoChangeNotify",
  "sw_mojing_control",
  sizeof(SwMojingControl__CloudStorageInfoChangeNotify),
  5,
  sw_mojing_control__cloud_storage_info_change_notify__field_descriptors,
  sw_mojing_control__cloud_storage_info_change_notify__field_indices_by_name,
  1,  sw_mojing_control__cloud_storage_info_change_notify__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__cloud_storage_info_change_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__pong__field_descriptors[2] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__Pong, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__Pong, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__pong__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__pong__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__pong__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.Pong",
  "Pong",
  "SwMojingControl__Pong",
  "sw_mojing_control",
  sizeof(SwMojingControl__Pong),
  2,
  sw_mojing_control__pong__field_descriptors,
  sw_mojing_control__pong__field_indices_by_name,
  1,  sw_mojing_control__pong__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__pong__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__register_response_with_nonce__field_descriptors[3] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterResponseWithNonce, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterResponseWithNonce, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterResponseWithNonce, nonce),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__register_response_with_nonce__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
  2,   /* field[2] = nonce */
};
static const ProtobufCIntRange sw_mojing_control__register_response_with_nonce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sw_mojing_control__register_response_with_nonce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.RegisterResponseWithNonce",
  "RegisterResponseWithNonce",
  "SwMojingControl__RegisterResponseWithNonce",
  "sw_mojing_control",
  sizeof(SwMojingControl__RegisterResponseWithNonce),
  3,
  sw_mojing_control__register_response_with_nonce__field_descriptors,
  sw_mojing_control__register_response_with_nonce__field_indices_by_name,
  1,  sw_mojing_control__register_response_with_nonce__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__register_response_with_nonce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_cloud_storage_addr_request__field_descriptors[7] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CloudStorageType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, cloudstoragetype),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StreamType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, streamtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PreStorageTime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, prestoragetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "KeepTime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, keeptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StreamDesc",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, streamdesc),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StartTime",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrRequest, starttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_cloud_storage_addr_request__field_indices_by_name[] = {
  1,   /* field[1] = CloudStorageType */
  0,   /* field[0] = DeviceID */
  4,   /* field[4] = KeepTime */
  3,   /* field[3] = PreStorageTime */
  6,   /* field[6] = StartTime */
  5,   /* field[5] = StreamDesc */
  2,   /* field[2] = StreamType */
};
static const ProtobufCIntRange sw_mojing_control__get_cloud_storage_addr_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_addr_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetCloudStorageAddrRequest",
  "GetCloudStorageAddrRequest",
  "SwMojingControl__GetCloudStorageAddrRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetCloudStorageAddrRequest),
  7,
  sw_mojing_control__get_cloud_storage_addr_request__field_descriptors,
  sw_mojing_control__get_cloud_storage_addr_request__field_indices_by_name,
  1,  sw_mojing_control__get_cloud_storage_addr_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_cloud_storage_addr_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__cloud_storage_end_notify__field_descriptors[4] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageEndNotify, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TaskID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageEndNotify, taskid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StartTime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageEndNotify, starttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EndTime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__CloudStorageEndNotify, endtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__cloud_storage_end_notify__field_indices_by_name[] = {
  0,   /* field[0] = DeviceID */
  3,   /* field[3] = EndTime */
  2,   /* field[2] = StartTime */
  1,   /* field[1] = TaskID */
};
static const ProtobufCIntRange sw_mojing_control__cloud_storage_end_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sw_mojing_control__cloud_storage_end_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.CloudStorageEndNotify",
  "CloudStorageEndNotify",
  "SwMojingControl__CloudStorageEndNotify",
  "sw_mojing_control",
  sizeof(SwMojingControl__CloudStorageEndNotify),
  4,
  sw_mojing_control__cloud_storage_end_notify__field_descriptors,
  sw_mojing_control__cloud_storage_end_notify__field_indices_by_name,
  1,  sw_mojing_control__cloud_storage_end_notify__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__cloud_storage_end_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_cloud_storage_info_request__field_descriptors[2] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoRequest, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoRequest, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_cloud_storage_info_request__field_indices_by_name[] = {
  0,   /* field[0] = DeviceID */
  1,   /* field[1] = Time */
};
static const ProtobufCIntRange sw_mojing_control__get_cloud_storage_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetCloudStorageInfoRequest",
  "GetCloudStorageInfoRequest",
  "SwMojingControl__GetCloudStorageInfoRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetCloudStorageInfoRequest),
  2,
  sw_mojing_control__get_cloud_storage_info_request__field_descriptors,
  sw_mojing_control__get_cloud_storage_info_request__field_indices_by_name,
  1,  sw_mojing_control__get_cloud_storage_info_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_cloud_storage_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_cloud_storage_info_response__field_descriptors[6] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CloudStorageType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, cloudstoragetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StreamType",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, streamtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PreStorageTime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, prestoragetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "KeepTime",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageInfoResponse, keeptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_cloud_storage_info_response__field_indices_by_name[] = {
  2,   /* field[2] = CloudStorageType */
  0,   /* field[0] = Code */
  5,   /* field[5] = KeepTime */
  1,   /* field[1] = Message */
  4,   /* field[4] = PreStorageTime */
  3,   /* field[3] = StreamType */
};
static const ProtobufCIntRange sw_mojing_control__get_cloud_storage_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetCloudStorageInfoResponse",
  "GetCloudStorageInfoResponse",
  "SwMojingControl__GetCloudStorageInfoResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetCloudStorageInfoResponse),
  6,
  sw_mojing_control__get_cloud_storage_info_response__field_descriptors,
  sw_mojing_control__get_cloud_storage_info_response__field_indices_by_name,
  1,  sw_mojing_control__get_cloud_storage_info_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_cloud_storage_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__register_request__field_descriptors[2] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequest, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RegisterTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequest, registertime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__register_request__field_indices_by_name[] = {
  0,   /* field[0] = DeviceID */
  1,   /* field[1] = RegisterTime */
};
static const ProtobufCIntRange sw_mojing_control__register_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__register_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.RegisterRequest",
  "RegisterRequest",
  "SwMojingControl__RegisterRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__RegisterRequest),
  2,
  sw_mojing_control__register_request__field_descriptors,
  sw_mojing_control__register_request__field_indices_by_name,
  1,  sw_mojing_control__register_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__register_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__device_update_request__field_descriptors[5] =
{
  {
    "UpdateType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateRequest, updatetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wareURL",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateRequest, wareurl),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wareVersion",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateRequest, wareversion),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wareMD5",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateRequest, waremd5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TaskID",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateRequest, taskid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__device_update_request__field_indices_by_name[] = {
  4,   /* field[4] = TaskID */
  0,   /* field[0] = UpdateType */
  3,   /* field[3] = wareMD5 */
  1,   /* field[1] = wareURL */
  2,   /* field[2] = wareVersion */
};
static const ProtobufCIntRange sw_mojing_control__device_update_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sw_mojing_control__device_update_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.DeviceUpdateRequest",
  "DeviceUpdateRequest",
  "SwMojingControl__DeviceUpdateRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__DeviceUpdateRequest),
  5,
  sw_mojing_control__device_update_request__field_descriptors,
  sw_mojing_control__device_update_request__field_indices_by_name,
  1,  sw_mojing_control__device_update_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__device_update_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__device_update_notify__field_descriptors[5] =
{
  {
    "UpdateType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateNotify, updatetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TaskID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateNotify, taskid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wareVersion",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateNotify, wareversion),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wareMD5",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateNotify, waremd5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UpdateTime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateNotify, updatetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__device_update_notify__field_indices_by_name[] = {
  1,   /* field[1] = TaskID */
  4,   /* field[4] = UpdateTime */
  0,   /* field[0] = UpdateType */
  3,   /* field[3] = wareMD5 */
  2,   /* field[2] = wareVersion */
};
static const ProtobufCIntRange sw_mojing_control__device_update_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sw_mojing_control__device_update_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.DeviceUpdateNotify",
  "DeviceUpdateNotify",
  "SwMojingControl__DeviceUpdateNotify",
  "sw_mojing_control",
  sizeof(SwMojingControl__DeviceUpdateNotify),
  5,
  sw_mojing_control__device_update_notify__field_descriptors,
  sw_mojing_control__device_update_notify__field_indices_by_name,
  1,  sw_mojing_control__device_update_notify__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__device_update_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__ping__field_descriptors[1] =
{
  {
    "Time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__Ping, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__ping__field_indices_by_name[] = {
  0,   /* field[0] = Time */
};
static const ProtobufCIntRange sw_mojing_control__ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sw_mojing_control__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.Ping",
  "Ping",
  "SwMojingControl__Ping",
  "sw_mojing_control",
  sizeof(SwMojingControl__Ping),
  1,
  sw_mojing_control__ping__field_descriptors,
  sw_mojing_control__ping__field_indices_by_name,
  1,  sw_mojing_control__ping__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__fromat_sdcard_request__field_descriptors[1] =
{
  {
    "Date",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__FromatSDCardRequest, date),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__fromat_sdcard_request__field_indices_by_name[] = {
  0,   /* field[0] = Date */
};
static const ProtobufCIntRange sw_mojing_control__fromat_sdcard_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sw_mojing_control__fromat_sdcard_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.FromatSDCardRequest",
  "FromatSDCardRequest",
  "SwMojingControl__FromatSDCardRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__FromatSDCardRequest),
  1,
  sw_mojing_control__fromat_sdcard_request__field_descriptors,
  sw_mojing_control__fromat_sdcard_request__field_indices_by_name,
  1,  sw_mojing_control__fromat_sdcard_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__fromat_sdcard_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__register_response__field_descriptors[2] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__register_response__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__register_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__register_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.RegisterResponse",
  "RegisterResponse",
  "SwMojingControl__RegisterResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__RegisterResponse),
  2,
  sw_mojing_control__register_response__field_descriptors,
  sw_mojing_control__register_response__field_indices_by_name,
  1,  sw_mojing_control__register_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__register_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_sdcard_info_request__field_descriptors[1] =
{
  {
    "Date",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(SwMojingControl__GetSDCardInfoRequest, n_date),
    offsetof(SwMojingControl__GetSDCardInfoRequest, date),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_sdcard_info_request__field_indices_by_name[] = {
  0,   /* field[0] = Date */
};
static const ProtobufCIntRange sw_mojing_control__get_sdcard_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_sdcard_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetSDCardInfoRequest",
  "GetSDCardInfoRequest",
  "SwMojingControl__GetSDCardInfoRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetSDCardInfoRequest),
  1,
  sw_mojing_control__get_sdcard_info_request__field_descriptors,
  sw_mojing_control__get_sdcard_info_request__field_indices_by_name,
  1,  sw_mojing_control__get_sdcard_info_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_sdcard_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__fromat_sdcard_stat_notify__field_descriptors[2] =
{
  {
    "FromatSDCardStat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__FromatSDCardStatNotify, fromatsdcardstat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__FromatSDCardStatNotify, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__fromat_sdcard_stat_notify__field_indices_by_name[] = {
  0,   /* field[0] = FromatSDCardStat */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__fromat_sdcard_stat_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__fromat_sdcard_stat_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.FromatSDCardStatNotify",
  "FromatSDCardStatNotify",
  "SwMojingControl__FromatSDCardStatNotify",
  "sw_mojing_control",
  sizeof(SwMojingControl__FromatSDCardStatNotify),
  2,
  sw_mojing_control__fromat_sdcard_stat_notify__field_descriptors,
  sw_mojing_control__fromat_sdcard_stat_notify__field_indices_by_name,
  1,  sw_mojing_control__fromat_sdcard_stat_notify__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__fromat_sdcard_stat_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__down_load_stat_request__field_descriptors[2] =
{
  {
    "DownLoadStat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DownLoadStatRequest, downloadstat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DownLoadStatRequest, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__down_load_stat_request__field_indices_by_name[] = {
  0,   /* field[0] = DownLoadStat */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__down_load_stat_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__down_load_stat_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.DownLoadStatRequest",
  "DownLoadStatRequest",
  "SwMojingControl__DownLoadStatRequest",
  "sw_mojing_control",
  sizeof(SwMojingControl__DownLoadStatRequest),
  2,
  sw_mojing_control__down_load_stat_request__field_descriptors,
  sw_mojing_control__down_load_stat_request__field_indices_by_name,
  1,  sw_mojing_control__down_load_stat_request__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__down_load_stat_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__upload_device_info_response__field_descriptors[2] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__UploadDeviceInfoResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__upload_device_info_response__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__upload_device_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__upload_device_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.UploadDeviceInfoResponse",
  "UploadDeviceInfoResponse",
  "SwMojingControl__UploadDeviceInfoResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__UploadDeviceInfoResponse),
  2,
  sw_mojing_control__upload_device_info_response__field_descriptors,
  sw_mojing_control__upload_device_info_response__field_indices_by_name,
  1,  sw_mojing_control__upload_device_info_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__upload_device_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__device_update_response__field_descriptors[2] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__DeviceUpdateResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__device_update_response__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__device_update_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__device_update_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.DeviceUpdateResponse",
  "DeviceUpdateResponse",
  "SwMojingControl__DeviceUpdateResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__DeviceUpdateResponse),
  2,
  sw_mojing_control__device_update_response__field_descriptors,
  sw_mojing_control__device_update_response__field_indices_by_name,
  1,  sw_mojing_control__device_update_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__device_update_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__register_request_with_auth__field_descriptors[4] =
{
  {
    "DeviceID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequestWithAuth, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RegisterTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequestWithAuth, registertime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Auth",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequestWithAuth, auth),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PingSpan",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__RegisterRequestWithAuth, pingspan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__register_request_with_auth__field_indices_by_name[] = {
  2,   /* field[2] = Auth */
  0,   /* field[0] = DeviceID */
  3,   /* field[3] = PingSpan */
  1,   /* field[1] = RegisterTime */
};
static const ProtobufCIntRange sw_mojing_control__register_request_with_auth__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sw_mojing_control__register_request_with_auth__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.RegisterRequestWithAuth",
  "RegisterRequestWithAuth",
  "SwMojingControl__RegisterRequestWithAuth",
  "sw_mojing_control",
  sizeof(SwMojingControl__RegisterRequestWithAuth),
  4,
  sw_mojing_control__register_request_with_auth__field_descriptors,
  sw_mojing_control__register_request_with_auth__field_indices_by_name,
  1,  sw_mojing_control__register_request_with_auth__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__register_request_with_auth__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_sdcard_info_response__field_descriptors[6] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SDStat",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, sdstat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SDCardSize",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, sdcardsize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SDCardAvailableSize",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, sdcardavailablesize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SDCardUsedSize",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetSDCardInfoResponse, sdcardusedsize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_sdcard_info_response__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
  4,   /* field[4] = SDCardAvailableSize */
  3,   /* field[3] = SDCardSize */
  5,   /* field[5] = SDCardUsedSize */
  2,   /* field[2] = SDStat */
};
static const ProtobufCIntRange sw_mojing_control__get_sdcard_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_sdcard_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetSDCardInfoResponse",
  "GetSDCardInfoResponse",
  "SwMojingControl__GetSDCardInfoResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetSDCardInfoResponse),
  6,
  sw_mojing_control__get_sdcard_info_response__field_descriptors,
  sw_mojing_control__get_sdcard_info_response__field_indices_by_name,
  1,  sw_mojing_control__get_sdcard_info_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_sdcard_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__operate_response__field_descriptors[2] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__OperateResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__OperateResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__operate_response__field_indices_by_name[] = {
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
};
static const ProtobufCIntRange sw_mojing_control__operate_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sw_mojing_control__operate_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.OperateResponse",
  "OperateResponse",
  "SwMojingControl__OperateResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__OperateResponse),
  2,
  sw_mojing_control__operate_response__field_descriptors,
  sw_mojing_control__operate_response__field_indices_by_name,
  1,  sw_mojing_control__operate_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__operate_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sw_mojing_control__get_cloud_storage_addr_response__field_descriptors[7] =
{
  {
    "Code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SSRC",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, ssrc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AddrIP",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, addrip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AddrPort",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, addrport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TransType",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, transtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TaskID",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SwMojingControl__GetCloudStorageAddrResponse, taskid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sw_mojing_control__get_cloud_storage_addr_response__field_indices_by_name[] = {
  3,   /* field[3] = AddrIP */
  4,   /* field[4] = AddrPort */
  0,   /* field[0] = Code */
  1,   /* field[1] = Message */
  2,   /* field[2] = SSRC */
  6,   /* field[6] = TaskID */
  5,   /* field[5] = TransType */
};
static const ProtobufCIntRange sw_mojing_control__get_cloud_storage_addr_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor sw_mojing_control__get_cloud_storage_addr_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sw_mojing_control.GetCloudStorageAddrResponse",
  "GetCloudStorageAddrResponse",
  "SwMojingControl__GetCloudStorageAddrResponse",
  "sw_mojing_control",
  sizeof(SwMojingControl__GetCloudStorageAddrResponse),
  7,
  sw_mojing_control__get_cloud_storage_addr_response__field_descriptors,
  sw_mojing_control__get_cloud_storage_addr_response__field_indices_by_name,
  1,  sw_mojing_control__get_cloud_storage_addr_response__number_ranges,
  (ProtobufCMessageInit) sw_mojing_control__get_cloud_storage_addr_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
